### ISSUE TITLE
ITS microcode

### ISSUE THREAD

**Issue by b4** [PDP-10/microcode#2]
Someone has it in a more accessible place than I do I bet.

**Comment by larsbrinkhoff** [comment]
I sent the ITS KS microcode to @jfcl:  
https://github.com/KS10FPGA/KS10FPGA/tree/master/microcode/ITS

**Comment by larsbrinkhoff** [comment]
I can submit a pull request with the KL microcode tomorrow.

**Comment by b4** [comment]
Alright - I'll merge it when you do.

**Comment by b4** [comment]
Merged. Closing.
